import { useEffect, useRef, useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Loader2, Download, Music, RefreshCw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

interface SheetMusicViewerProps {
  songId: number;
  abcNotation?: string | null;
  songTitle: string;
}

export default function SheetMusicViewer({ songId, abcNotation: initialAbc, songTitle }: SheetMusicViewerProps) {
  const sheetRef = useRef<HTMLDivElement>(null);
  const [abc, setAbc] = useState<string | null>(initialAbc ?? null);
  const [isRendered, setIsRendered] = useState(false);
  const generateMutation = trpc.songs.generateSheetMusic.useMutation();
  const utils = trpc.useUtils();

  const handleGenerate = useCallback(async () => {
    try {
      const result = await generateMutation.mutateAsync({ songId });
      setAbc(result.abcNotation);
      utils.songs.getById.invalidate({ id: songId });
      toast.success("Sheet music generated!");
    } catch (error: any) {
      toast.error(error.message || "Failed to generate sheet music");
    }
  }, [songId, generateMutation, utils]);

  // Render ABC notation using abcjs
  useEffect(() => {
    if (!abc || !sheetRef.current) return;

    setIsRendered(false);

    // Dynamic import of abcjs
    import("abcjs").then((abcjs) => {
      if (!sheetRef.current) return;
      sheetRef.current.innerHTML = "";
      abcjs.renderAbc(sheetRef.current, abc, {
        responsive: "resize",
        staffwidth: 700,
        paddingtop: 20,
        paddingbottom: 20,
        paddingleft: 15,
        paddingright: 15,
        add_classes: true,
      });
      setIsRendered(true);
    }).catch(() => {
      toast.error("Failed to render sheet music");
    });
  }, [abc]);

  const handleDownloadPDF = useCallback(async () => {
    if (!sheetRef.current) return;

    const svgElement = sheetRef.current.querySelector("svg");
    if (!svgElement) {
      toast.error("No sheet music to export");
      return;
    }

    try {
      // Clone SVG and set explicit dimensions for PDF
      const svgClone = svgElement.cloneNode(true) as SVGElement;
      const svgWidth = svgElement.getBoundingClientRect().width;
      const svgHeight = svgElement.getBoundingClientRect().height;

      svgClone.setAttribute("width", String(svgWidth));
      svgClone.setAttribute("height", String(svgHeight));

      // Create a canvas to render SVG
      const canvas = document.createElement("canvas");
      const scale = 2; // High-res for print
      canvas.width = svgWidth * scale;
      canvas.height = svgHeight * scale;
      const ctx = canvas.getContext("2d")!;
      ctx.scale(scale, scale);
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, svgWidth, svgHeight);

      const svgData = new XMLSerializer().serializeToString(svgClone);
      const svgBlob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" });
      const url = URL.createObjectURL(svgBlob);

      const img = new Image();
      img.onload = () => {
        ctx.drawImage(img, 0, 0, svgWidth, svgHeight);
        URL.revokeObjectURL(url);

        // Convert to PDF using jsPDF-like approach via canvas
        canvas.toBlob((blob) => {
          if (!blob) return;
          // Create a simple printable HTML page with the image
          const imageUrl = URL.createObjectURL(blob);
          const printWindow = window.open("", "_blank");
          if (printWindow) {
            printWindow.document.write(`
              <!DOCTYPE html>
              <html>
              <head>
                <title>${songTitle} - Sheet Music</title>
                <style>
                  @page { size: A4; margin: 1cm; }
                  body { margin: 0; padding: 20px; font-family: 'Georgia', serif; }
                  h1 { text-align: center; font-size: 24px; margin-bottom: 5px; }
                  .subtitle { text-align: center; color: #666; font-size: 14px; margin-bottom: 20px; }
                  img { width: 100%; max-width: 100%; }
                  .footer { text-align: center; color: #999; font-size: 10px; margin-top: 20px; }
                  @media print { .no-print { display: none; } }
                </style>
              </head>
              <body>
                <h1>${songTitle}</h1>
                <div class="subtitle">Sheet Music &bull; Generated by AI Music Generator</div>
                <img src="${imageUrl}" alt="Sheet Music" />
                <div class="footer">Generated with AI Music Generator &bull; makecustommusic.com</div>
                <div class="no-print" style="text-align:center;margin-top:20px;">
                  <button onclick="window.print()" style="padding:10px 24px;font-size:16px;cursor:pointer;background:#6366f1;color:white;border:none;border-radius:8px;">
                    Print / Save as PDF
                  </button>
                </div>
              </body>
              </html>
            `);
            printWindow.document.close();
          }
        }, "image/png");
      };
      img.src = url;

      toast.success("Sheet music ready for print/download!");
    } catch {
      toast.error("Failed to export sheet music");
    }
  }, [songTitle]);

  // No ABC notation yet — show generate button
  if (!abc) {
    return (
      <div className="flex flex-col items-center justify-center py-12 space-y-4">
        <Music className="w-12 h-12 text-muted-foreground/40" />
        <div className="text-center space-y-1">
          <p className="text-sm font-medium text-foreground">No sheet music yet</p>
          <p className="text-xs text-muted-foreground">
            Generate a professional lead sheet with melody notation and chord symbols
          </p>
        </div>
        <Button
          onClick={handleGenerate}
          disabled={generateMutation.isPending}
          className="gap-2"
        >
          {generateMutation.isPending ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Generating Sheet Music...
            </>
          ) : (
            <>
              <Music className="w-4 h-4" />
              Generate Sheet Music
            </>
          )}
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Action bar */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Music className="w-4 h-4 text-primary" />
          <span className="text-sm font-medium">Lead Sheet</span>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadPDF}
            disabled={!isRendered}
            className="gap-1.5"
          >
            <Download className="w-3.5 h-3.5" />
            Print / PDF
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleGenerate}
            disabled={generateMutation.isPending}
            className="gap-1.5"
          >
            {generateMutation.isPending ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5" />
            )}
            Regenerate
          </Button>
        </div>
      </div>

      {/* Sheet music rendering area */}
      <div
        ref={sheetRef}
        className="bg-white rounded-lg border border-border p-4 min-h-[200px] overflow-x-auto"
        style={{ colorScheme: "light" }}
      />
    </div>
  );
}
